### ISSUE TITLE
Add source for Jira issues/keys

### ISSUE THREAD

**Issue by anrie** [axieax/urlview.nvim#11]
Thanks a lot for this useful plugin!

It would be great if the plugin could also handle keys for Jira issues (e.g. `PROJECT-1234`), so that one can browse referenced issues and open them in the browser.

Not sure if the assumption is to simplistic, but for most projects it might suffice if one could define env vars for the `JIRA_BASE_URL` (e.g. `https://your-jira-url.com/browse/) `and a `JIRA_ISSUE_PATTERN` (probably [along these lines](https://community.atlassian.com/t5/Jira-Software-questions/Postgres-regex-to-find-issue-keys-in-description-or-comments/qaq-p/1724619#M145702)).

**Comment by axieax** [comment]
Thanks for putting the feature request here :))
You can now register custom searches in the `setup` function, e.g.
```lua
require("urlview").setup({
	custom_searches = {
		jira = {
			capture = "AXIE%-%d+",
			format = "https://jira.axieax.com/browse/%s",
		},
	},
})
```

**Comment by anrie** [comment]
Now that was quick! Thanks a lot for this adding this feature!
