### ISSUE TITLE
Overriding settings like title and navigate_method has no effect

### ISSUE THREAD

**Issue by anrie** [axieax/urlview.nvim#13]
Hi!

not sure if this is simply a configuration mistake on my side, but I have issues defining certain settings, namely `title` and `navigate_method`.

This is what my setup function looks like:

```lua
require("urlview").setup({
    title = "Urls: ",
    default_picker = "telescope",
    navigate_method = "firefox",
})
```

What confuses me, is that changing the default picker has an effect. I can switch from telescope to the standard picker.
The `title` however is not picked up and the `navigate_method` also has no effect:

```Error executing lua ...ite/pack/packer/start/urlview.nvim/lua/urlview/utils.lua:31: Vim(call):E117: Unbekannte Funktion: netrw#CheckIfRemote ``` .. which makes sense in a sense, as I have disabled `netrw`.

If I edit the plugin defaults directly in my checked out `lua/urlview/config.lua` things work however. 
At first I suspected an issue with my packer config, but then it's strange, that changing some settings works and changing others doesn't.

**Comment by axieax** [comment]
Should be fixed now. Sorry for the inconvenience!

**Comment by anrie** [comment]
Thanks a lot!
