### ISSUE TITLE
URLs for packer.nvim config

### ISSUE THREAD

**Issue by axieax** [axieax/urlview.nvim#2]
Ability to detect patterns for `author/repo` in `use` functions, which can be displayed and upon selection, navigates to the corresponding GitHub page. 

Tasks:

- [x] Expose API, where users can provide a custom buffer number or file path (find bufnr to be passed in) so this list is accessible anywhere
- [ ] Ability to customise and define functions with the API (make more modular)
- [ ] Find pattern for detecting `author/repo` rules
- [ ] Add documentation -> wiki or sample.md

Notes:

- May need [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) to more accurately detect URLs?

**Comment by dhruvmanila** [comment]
You can directly use the `packer_plugins` global table which contains information regarding every plugin defined along with it's url and installed path. That's what I use for my [custom extension](https://github.com/dhruvmanila/dotfiles/blob/master/config/nvim/lua/telescope/_extensions/custom/installed_plugins.lua).
