### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by lopi-py** [axieax/urlview.nvim#41]
Minimal plugin but useful!
I was researching if there is a command for opening a url on windows and I found `start`. eg: `start https://github.com`. this will open that url with the system's default browser

**Comment by axieax** [comment]
Hi this would be a great addition to the plugin! I was planning on adding this (as part of the roadmap), but am not sure about how it’ll work with WSL1 and WSL2 (don’t have an environment to test it on). Feel free to create a PR if you want, or I can just add in the Windows case for now!

**Comment by lopi-py** [comment]
I think on wsl it will detect as linux, but I'm going to try now

**Comment by lopi-py** [comment]
It works on wsl, it use `xdg-open`, I don't have a "linux native" environment so I don't know it that is expected or it's wsl stuff but I'm getting a little delay(terminal freezing) when using it
