### ISSUE TITLE
Feature request: view urls on current line or select lines

### ISSUE THREAD

**Issue by linrongbin16** [axieax/urlview.nvim#45]
Hi, thanks to this plugin first. I use it a lot.

there are many times, my cursor is on a line with url.
And I want to open it.

please support view urls on current line or select lines.

**Comment by linrongbin16** [comment]
The first one would work for me.
I feel I missed something and need to read your doc again.

**Comment by axieax** [comment]
Great to hear! Feel free to reopen if you have anymore issues or suggestions!
