### ISSUE TITLE
Feature Request: Export Action

### ISSUE THREAD

**Issue by kevintraver** [axieax/urlview.nvim#54]
It would be awesome if there was an action to export the list of Urls.

Perhaps into a new buffer?

**Comment by kevintraver** [comment]
This can actually be done using telescope and then passing to quickfix, so Ill go ahead and close.

**Comment by axieax** [comment]
That's actually a great solution, love it! 🧠

**Comment by kevintraver** [comment]
The telescope integration is great!

What would also be awesome if the position information (line/column) could get saved into telescope (and then quickfix).

That would searching/moving between them even easier.

Ill look into how telescope does it with some of the other pickers.
