### ISSUE TITLE
Provide a way to customize the command to open URL

### ISSUE THREAD

**Issue by mars90226** [axieax/urlview.nvim#9]
First, thank you for this plugin!

I would like to ask for the feature to customize the command to open URL. Currently, it only use netrw or xdg-open (on Linux) to open URL. But users (like me) may want to use other command or vim command from other vim plugin to open it, like [open-browser.vim](https://github.com/tyru/open-browser.vim).

Maybe you can provide a config to customize command or execute certain vim command if it exists?
For example, [vim-fugitive](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L7217-L7219) try to open URL by using `:Browse` or `:OpenBrowser`.

Thank you!

**Comment by axieax** [comment]
Hi, thanks for the suggestion! open-browser.vim seems to open the requested browser using a shell command (#7 added some defaults for that) and vim-fugitive seems to use netrw (which is used by this plugin by default). I can add a config option to specify a browser to open with (controls the shell command to open the url with).

**Comment by mars90226** [comment]
Thank you! I'll try the new option.
